-- CREATE TABLES IN SPECIFIC ORDER
CREATE TABLE customers
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    phone VARCHAR(12),
    created_by VARCHAR(50) NOT NULL,
    created_on TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(50) NOT NULL,
    updated_on TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Creates a Foreign Key to customer table
CREATE TABLE addresses
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER REFERENCES customers (id),
    steet VARCHAR(100) NOT NULL,
    city VARCHAR(50) NOT NULL,
    state VARCHAR(50) NOT NULL,
    zip VARCHAR(50) NOT NULL
);


CREATE TABLE orders
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER REFERENCES customers (id),
    order_date TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Really should be a lookup table, but demo purposes this will do
    status VARCHAR(50) NOT NULL
);

CREATE TABLE products
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    image_name VARCHAR(100) NULL,
    list_price DECIMAL(10,2) NOT NULL
);


CREATE TABLE order_details
(
    order_id INTEGER REFERENCES orders (id),
    product_id INTEGER REFERENCES products (id),
    quantity INTEGER NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (order_id, product_id)

);
